import {
  Details,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Quote,
  Summary,
  TBody,
  TD,
  TFoot,
  TH,
  THead,
  TR,
  Table,
} from "./block-components";
import { Anchor, Code, InlineCode, Strong } from "./format-components";
import { ListItem, OrderedList, UnorderdList } from "./list-components";

export const mdxComponents = {
  h2: Heading2,
  h3: Heading3,
  h4: Heading4,
  h5: Heading5,
  h6: Heading6,
  ol: OrderedList,
  ul: UnorderdList,
  blockquote: Quote,
  code: InlineCode,
  Code,
  a: Anchor,
  li: ListItem,
  table: Table,
  thead: THead,
  tbody: TBody,
  tfoot: TFoot,
  tr: TR,
  td: TD,
  th: TH,
  details: Details,
  summary: Summary,
  strong: Strong,
};
